* update

diff --git a/scripts/variables b/scripts/variables
--- a/scripts/variables
+++ b/scripts/variables
@@ -1,14 +1,16 @@
 #!/bin/bash
-if [[ -f /usr/bin/xanadu-install ]]; then
-mkdir -p /run/xanadu
-clear
-else
-echo "El sistema no esta instalado, ejecute ./xanadu install"
-exit 1
-fi
+# Made by Sinfallas <sinfallas@yahoo.com>
+# Licence: GPL-2
 if [[ $USER != root ]]; then
-echo "Error: Debe tener privilegios de ROOT"
-exit 1
+	echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
+	exit 1
+fi
+if [[ -f /usr/bin/xanadu-install ]]; then
+	mkdir -p /run/xanadu
+	clear
+	else
+	echo "El sistema no esta instalado, ejecute ./xanadu install"
+	exit 1
 fi
 #----------
 nombre="sinfallas"
